import { AppDefinition } from '@/types';

export const APPS: AppDefinition[] = [
  { id: 'messenger',    title: 'Чайка Мессенджер',        icon: '🕊️', description: 'Мессенджер Чайка', defaultWidth: 820, defaultHeight: 600, minWidth: 400, minHeight: 350 },
  { id: 'notepad',      title: 'Блокнот',                 icon: '📝', description: 'Текстовый редактор', defaultWidth: 600, defaultHeight: 450, minWidth: 300, minHeight: 200 },
  { id: 'calculator',   title: 'Калькулятор',             icon: '🧮', description: 'Стандартный калькулятор', defaultWidth: 280, defaultHeight: 380, minWidth: 280, minHeight: 380 },
  { id: 'filemanager',  title: 'Проводник',               icon: '📁', description: 'Файловый менеджер', defaultWidth: 780, defaultHeight: 520, minWidth: 400, minHeight: 300 },
  { id: 'browser',      title: 'Браузер',                 icon: '🌐', description: 'Веб-браузер', defaultWidth: 900, defaultHeight: 620, minWidth: 400, minHeight: 300 },
  { id: 'settings',     title: 'Персонализация',          icon: '⚙️', description: 'Настройки рабочего стола', defaultWidth: 680, defaultHeight: 500, minWidth: 400, minHeight: 350 },
  { id: 'paint',        title: 'Paint',                   icon: '🎨', description: 'Графический редактор', defaultWidth: 800, defaultHeight: 560, minWidth: 400, minHeight: 300 },
  { id: 'admin',        title: 'Администрирование',       icon: '🛡️', description: 'Панель администратора', defaultWidth: 920, defaultHeight: 660, minWidth: 600, minHeight: 450 },
  { id: 'word',         title: 'Word',                    icon: '📄', description: 'Текстовый процессор', defaultWidth: 900, defaultHeight: 680, minWidth: 500, minHeight: 400 },
  { id: 'excel',        title: 'Excel',                   icon: '📊', description: 'Таблицы', defaultWidth: 900, defaultHeight: 620, minWidth: 500, minHeight: 380 },
  { id: 'rigonda',      title: 'Ригонда',                 icon: '📻', description: 'Проигрыватель музыки', defaultWidth: 300, defaultHeight: 560, minWidth: 290, minHeight: 200 },
  { id: 'crm',          title: 'CRM-система',             icon: '👥', description: 'Управление клиентами', defaultWidth: 960, defaultHeight: 660, minWidth: 600, minHeight: 400 },
  { id: 'russia',       title: 'Я-Россия',                icon: '🇷🇺', description: 'Информационный портал', defaultWidth: 900, defaultHeight: 660, minWidth: 500, minHeight: 400 },
  { id: 'solitaire',    title: 'Косынка',                 icon: '♠',  description: 'Классический пасьянс', defaultWidth: 860, defaultHeight: 600, minWidth: 540, minHeight: 440 },
  { id: 'ide',          title: 'Конструктор приложений',  icon: '💻', description: 'IDE для создания приложений', defaultWidth: 1060, defaultHeight: 700, minWidth: 700, minHeight: 500 },
  { id: 'max',          title: 'Мессенджер Макс',         icon: '💬', description: 'Мессенджер от Mail.ru', defaultWidth: 900, defaultHeight: 650, minWidth: 400, minHeight: 300 },
  { id: 'gosuslugi',    title: 'Госуслуги',               icon: '🏛️', description: 'Портал государственных услуг', defaultWidth: 1000, defaultHeight: 680, minWidth: 400, minHeight: 300 },
  { id: 'vk',           title: 'ВКонтакте',               icon: '🔵', description: 'Социальная сеть', defaultWidth: 1000, defaultHeight: 680, minWidth: 400, minHeight: 300 },
  { id: 'yandex',       title: 'Яндекс',                  icon: '🔴', description: 'Яндекс — поисковая система', defaultWidth: 1000, defaultHeight: 680, minWidth: 400, minHeight: 300 },
  { id: 'rutube',       title: 'Rutube',                  icon: '📺', description: 'Российский видеохостинг', defaultWidth: 1000, defaultHeight: 680, minWidth: 400, minHeight: 300 },
  { id: 'mail',         title: 'Почта Mail.ru',           icon: '📧', description: 'Почтовый сервис', defaultWidth: 950, defaultHeight: 660, minWidth: 400, minHeight: 300 },
  { id: 'ok',           title: 'Одноклассники',           icon: '🟠', description: 'Социальная сеть', defaultWidth: 1000, defaultHeight: 680, minWidth: 400, minHeight: 300 },
  { id: 'tumba',        title: 'Тумба',                   icon: '▶',  description: 'Российский видеохостинг', defaultWidth: 1020, defaultHeight: 700, minWidth: 600, minHeight: 450 },
  // ── Чайка v31 — Новые приложения ──
  { id: 'bjs',          title: 'Чайка BJS',               icon: '⌨️', description: 'Облачная среда разработки с AI', defaultWidth: 1100, defaultHeight: 720, minWidth: 700, minHeight: 500 },
  { id: 'ya-russia-new',title: 'Я-Россия: Аналитика',    icon: '📈', description: 'Экономика России в реальном времени', defaultWidth: 1000, defaultHeight: 680, minWidth: 600, minHeight: 400 },
  { id: 'aerotunnel',   title: 'Чайк.АДТ',               icon: '🌀', description: 'Аэродинамическая труба — симуляция', defaultWidth: 980, defaultHeight: 680, minWidth: 600, minHeight: 400 },
  { id: 'chaika-bin',   title: 'Чайка.BIN',              icon: '🔲', description: 'ASIC/x86 моделирование и отладка', defaultWidth: 1060, defaultHeight: 700, minWidth: 700, minHeight: 500 },
  { id: 'konstruktor',  title: 'КонструкторПлат',        icon: '🔌', description: 'PCB-редактор с AI для электроники', defaultWidth: 1100, defaultHeight: 720, minWidth: 700, minHeight: 500 },
  { id: 'treugolnik',   title: 'Треугольник',            icon: '🔺', description: 'Соцсеть для визуальных историй', defaultWidth: 980, defaultHeight: 680, minWidth: 500, minHeight: 400 },
  { id: 'obsmneniye',   title: 'Общественное мнение',    icon: '🗣️', description: 'Платформа обращений граждан', defaultWidth: 980, defaultHeight: 680, minWidth: 500, minHeight: 400 },
  { id: 'rubicad',      title: 'RubiCAD',                icon: '📐', description: 'CAD-система в браузере по ГОСТ', defaultWidth: 1100, defaultHeight: 720, minWidth: 700, minHeight: 500 },
  { id: 'vagner',       title: 'Наследие Вагнер',        icon: '🎮', description: 'Тактический шутер от первого лица', defaultWidth: 1000, defaultHeight: 680, minWidth: 600, minHeight: 450 },
  { id: 'marketplus',   title: 'МаркетПлюс',             icon: '🛒', description: 'Онлайн-маркетплейс с доставкой по РФ', defaultWidth: 1000, defaultHeight: 680, minWidth: 500, minHeight: 400 },
  { id: 'knopochki',    title: 'Кнопочки',               icon: '📌', description: 'Вдохновение и коллекции изображений', defaultWidth: 980, defaultHeight: 680, minWidth: 500, minHeight: 400 },
  { id: 'ini-fw',       title: 'INI.framework',          icon: '⚙️', description: 'Конфигурационная платформа INI', defaultWidth: 900, defaultHeight: 640, minWidth: 500, minHeight: 400 },
  { id: 'biolab',       title: 'Чайка.BioLab',           icon: '🧬', description: 'Цифровая научная лаборатория', defaultWidth: 1000, defaultHeight: 680, minWidth: 600, minHeight: 400 },
  { id: 'chaika-doc',   title: 'Чайка.DOC',              icon: '📋', description: 'Офисный пакет с AI-ассистентом', defaultWidth: 1060, defaultHeight: 700, minWidth: 600, minHeight: 450 },
  { id: 'sysconfig',    title: 'Системный конфигуратор', icon: '🔧', description: 'Arduino/RPi/Repka Pi — INI-файлы, HASP, GPIO', defaultWidth: 1020, defaultHeight: 700, minWidth: 700, minHeight: 500 },
  { id: 'commander',    title: 'Командер',               icon: '📂', description: 'Двухпанельный файловый менеджер с командной строкой', defaultWidth: 1000, defaultHeight: 680, minWidth: 700, minHeight: 480 },
  // ── Чайка v32 — Новые встроенные приложения ──
  { id: 'weather',       title: 'Погода',                 icon: '☁️', description: 'Реальные данные open-meteo.com — прогноз на 7 дней', defaultWidth: 440, defaultHeight: 680, minWidth: 380, minHeight: 500 },
  { id: 'currency',      title: 'Курсы валют',            icon: '💱', description: 'Конвертер 170+ валют — open.er-api.com', defaultWidth: 700, defaultHeight: 580, minWidth: 500, minHeight: 420 },
  { id: 'pomodoro',      title: 'Таймер Помодоро',        icon: '🍅', description: 'Техника помодоро: 25/5 мин, задачи', defaultWidth: 720, defaultHeight: 520, minWidth: 600, minHeight: 440 },
  { id: 'markdown',      title: 'Markdown-редактор',      icon: '📝', description: 'Живой предпросмотр Markdown', defaultWidth: 900, defaultHeight: 620, minWidth: 600, minHeight: 400 },
  { id: 'passgen',       title: 'Генератор паролей',      icon: '🔑', description: 'Криптографически стойкие пароли', defaultWidth: 480, defaultHeight: 640, minWidth: 420, minHeight: 500 },
  { id: 'worldclock',    title: 'Мировые часы',           icon: '🌍', description: 'Часы в любом часовом поясе', defaultWidth: 820, defaultHeight: 560, minWidth: 600, minHeight: 420 },
  { id: 'jsontool',      title: 'JSON-инструмент',        icon: '{}', description: 'Форматирование, минификация, дерево JSON', defaultWidth: 900, defaultHeight: 620, minWidth: 700, minHeight: 450 },
  { id: 'translator',    title: 'Переводчик',             icon: '🌐', description: 'Перевод на 20+ языков через MyMemory', defaultWidth: 680, defaultHeight: 580, minWidth: 500, minHeight: 440 },
  { id: 'qrgen',         title: 'QR-генератор',           icon: '⊞',  description: 'Создание QR-кодов для URL, WiFi, контактов', defaultWidth: 680, defaultHeight: 540, minWidth: 560, minHeight: 440 },
  { id: 'passport',      title: 'Цифровой паспорт',       icon: '🪪', description: 'Профиль · OAuth-приложения · Безопасность', defaultWidth: 760, defaultHeight: 620, minWidth: 600, minHeight: 480 },
  { id: 'osm',           title: 'Карты',                  icon: '🗺️', description: 'OpenStreetMap в браузере', defaultWidth: 1000, defaultHeight: 680, minWidth: 600, minHeight: 400 },
];

// Desktop icons — cosmic theme
export const DESKTOP_ICONS = [
  { appId: 'filemanager',  label: 'Мой компьютер', icon: 'cosmic-computer'   },
  { appId: 'filemanager',  label: 'Документы',     icon: 'cosmic-documents'  },
  { appId: 'messenger',    label: 'Чайка',          icon: 'cosmic-messenger'  },
  { appId: 'tumba',        label: 'Тумба',          icon: 'cosmic-tumba'      },
  { appId: 'settings',     label: 'Настройки',     icon: 'cosmic-settings'   },
  { appId: 'solitaire',    label: 'Косынка',        icon: 'cosmic-solitaire'  },
  { appId: 'bjs',          label: 'Чайка BJS',      icon: 'cosmic-bjs'        },
  { appId: 'treugolnik',   label: 'Треугольник',    icon: 'cosmic-treugolnik' },
  { appId: 'sysconfig',    label: 'Конфигуратор',   icon: 'cosmic-bin'        },
  { appId: 'commander',    label: 'Командер',        icon: 'cosmic-documents'  },
];

// All built-in app IDs for menus — NO separation between "internet" and "standard"
export const ALL_APP_IDS = [
  { id: 'messenger',     label: 'Чайка Мессенджер',       section: 'Связь'        },
  { id: 'filemanager',   label: 'Проводник',               section: 'Система'      },
  { id: 'notepad',       label: 'Блокнот',                 section: 'Система'      },
  { id: 'calculator',    label: 'Калькулятор',             section: 'Система'      },
  { id: 'browser',       label: 'Браузер',                 section: 'Система'      },
  { id: 'settings',      label: 'Персонализация',          section: 'Система'      },
  { id: 'paint',         label: 'Paint',                   section: 'Система'      },
  { id: 'solitaire',     label: 'Косынка',                 section: 'Игры'         },
  { id: 'vagner',        label: 'Наследие Вагнер',         section: 'Игры'         },
  { id: 'ide',           label: 'Конструктор приложений',  section: 'Система'      },
  { id: 'word',          label: 'Word',                    section: 'Офис'         },
  { id: 'excel',         label: 'Excel',                   section: 'Офис'         },
  { id: 'chaika-doc',    label: 'Чайка.DOC',               section: 'Офис'         },
  { id: 'rigonda',       label: 'Ригонда',                 section: 'Медиа'        },
  { id: 'tumba',         label: 'Тумба',                   section: 'Медиа'        },
  { id: 'knopochki',     label: 'Кнопочки',                section: 'Медиа'        },
  { id: 'crm',           label: 'CRM-система',             section: 'Бизнес'       },
  { id: 'marketplus',    label: 'МаркетПлюс',              section: 'Бизнес'       },
  { id: 'admin',         label: 'Администрирование',       section: 'Система'      },
  { id: 'russia',        label: 'Я-Россия',                section: 'Интернет'     },
  { id: 'ya-russia-new', label: 'Я-Россия: Аналитика',    section: 'Интернет'     },
  { id: 'vk',            label: 'ВКонтакте',               section: 'Интернет'     },
  { id: 'ok',            label: 'Одноклассники',           section: 'Интернет'     },
  { id: 'max',           label: 'Мессенджер Макс',         section: 'Интернет'     },
  { id: 'gosuslugi',     label: 'Госуслуги',               section: 'Интернет'     },
  { id: 'yandex',        label: 'Яндекс',                  section: 'Интернет'     },
  { id: 'rutube',        label: 'Rutube',                  section: 'Интернет'     },
  { id: 'mail',          label: 'Почта Mail.ru',           section: 'Интернет'     },
  { id: 'treugolnik',    label: 'Треугольник',             section: 'Интернет'     },
  { id: 'obsmneniye',    label: 'Общественное мнение',     section: 'Интернет'     },
  { id: 'bjs',           label: 'Чайка BJS',               section: 'Разработка'   },
  { id: 'chaika-bin',    label: 'Чайка.BIN',               section: 'Разработка'   },
  { id: 'konstruktor',   label: 'КонструкторПлат',         section: 'Разработка'   },
  { id: 'ini-fw',        label: 'INI.framework',           section: 'Разработка'   },
  { id: 'aerotunnel',    label: 'Чайк.АДТ',                section: 'Наука'        },
  { id: 'biolab',        label: 'Чайка.BioLab',            section: 'Наука'        },
  { id: 'rubicad',       label: 'RubiCAD',                 section: 'Наука'        },
  { id: 'sysconfig',   label: 'Системный конфигуратор',  section: 'Разработка'   },
  { id: 'commander',   label: 'Командер',                 section: 'Система'      },
  { id: 'weather',     label: 'Погода',                   section: 'Система'      },
  { id: 'currency',    label: 'Курсы валют',               section: 'Система'      },
  { id: 'pomodoro',    label: 'Таймер Помодоро',           section: 'Система'      },
  { id: 'markdown',    label: 'Markdown-редактор',         section: 'Офис'         },
  { id: 'passgen',     label: 'Генератор паролей',         section: 'Система'      },
  { id: 'worldclock',  label: 'Мировые часы',              section: 'Система'      },
  { id: 'jsontool',    label: 'JSON-инструмент',           section: 'Разработка'   },
  { id: 'translator',  label: 'Переводчик',                section: 'Система'      },
  { id: 'qrgen',       label: 'QR-генератор',              section: 'Система'      },
  { id: 'passport',    label: 'Цифровой паспорт',          section: 'Система'      },
  { id: 'osm',         label: 'Карты',                     section: 'Интернет'     },
  // v32.1
  { id: 'unitconv',    label: 'Конвертер единиц',           section: 'Утилиты'      },
  { id: 'timer',       label: 'Таймер',                     section: 'Утилиты'      },
  { id: 'hashtool',    label: 'Хеш-инструмент',             section: 'Разработка'   },
  { id: 'appstore',    label: 'Магазин приложений',         section: 'Система'      },
  { id: 'dzen',        label: 'Дзен',                       section: 'Интернет'     },
  { id: 'rbc',         label: 'РБК',                        section: 'Интернет'     },
  { id: 'lenta',       label: 'Lenta.ru',                   section: 'Интернет'     },
  { id: 'kinopoisk',   label: 'Кинопоиск',                  section: 'Медиа'        },
  { id: 'hh',          label: 'HeadHunter',                 section: 'Интернет'     },
  { id: 'avito',       label: 'Авито',                      section: 'Интернет'     },
  { id: '2gis',        label: '2ГИС',                       section: 'Интернет'     },
  { id: 'habr',        label: 'Хабр',                       section: 'Разработка'   },
  { id: 'pikabu',      label: 'Пикабу',                     section: 'Интернет'     },
  { id: 'wikipedia',   label: 'Википедия',                  section: 'Интернет'     },
  { id: 'ozon',        label: 'Ozon',                       section: 'Интернет'     },
  { id: 'wildberries', label: 'Wildberries',                section: 'Интернет'     },
  { id: 'ria',         label: 'РИА Новости',                section: 'Интернет'     },
  { id: 'iz',          label: 'Известия',                   section: 'Интернет'     },
  { id: 'yandex-music',label: 'Яндекс.Музыка',              section: 'Медиа'        },
  { id: 'yandex-news', label: 'Яндекс.Новости',             section: 'Интернет'     },
  { id: 'yandex-maps', label: 'Яндекс.Карты',              section: 'Интернет'     },
  { id: 'yandex-disk', label: 'Яндекс.Диск',               section: 'Система'      },
  { id: 'tinkoff',     label: 'Т-Банк',                     section: 'Интернет'     },
  { id: 'sber',        label: 'СберБанк',                   section: 'Интернет'     },
  { id: 'stepik',      label: 'Stepik',                     section: 'Интернет'     },
  { id: 'github',      label: 'GitHub',                     section: 'Разработка'   },
  { id: 'stackoverflow',label: 'Stack Overflow',            section: 'Разработка'   },
  { id: 'figma',       label: 'Figma',                      section: 'Разработка'   },
  { id: 'netologia',   label: 'Нетология',                  section: 'Интернет'     },
];

export const START_MENU_APPS = ALL_APP_IDS;
